---
# yaml-language-server: $schema=https://github.com/Twingate/helm-charts/blob/eb45ff70cde6ccfb076b23597cb26d96624e2842/stable/connector/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate-backup
  namespace: network
spec:
  interval: 10m
  chart:
    spec:
      chart: connector
      version: 0.1.27
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: twingate/connector
      tag: 1.74.0
    connector:
      logLevel: "info"
      network: bitbybit
      url: "twingate.com"
      existingSecret: twingatebackup-secret
      dnsServer: 10.10.13.5,10.10.13.6
